# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - nutriec-backend-angel01
name: Deploy NutriEc backend to Azure Web App - nutriec-backend-angel01

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies (prod)
        run: npm ci --omit=dev

      - name: Create deploy package
        run: |
          zip -r release.zip . -x ".git/*" ".github/*" "*.env"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_01DC8978E3A344DEA3668C9CE8766C52 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B9748F8DE9B5456BB8A1E135FC176C02 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1EABD576E9AD4161873EAA149774511C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: nutriec-backend-angel01
          slot-name: Production
          package: release.zip